[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "optiflowx"
version = "0.0.5"
requires-python = ">=3.10"
description = "A modular optimization and machine learning workflow framework for automatic model selection, hyperparameter tuning, and performance benchmarking across diverse datasets."
readme = "README.md"
authors = [{ name = "Alikacem Faycal", email = "faycal213.dz@gmail.com" }]
dependencies = ["numpy", "scikit-learn", "tqdm", "optuna", "scikit-optimize", "xgboost"]
keywords = [
  "hyperparameter optimization",
  "AutoML",
  "combinatorial optimization",
  "machine learning",
  "genetic algorithm",
  "particle swarm optimization",
  "bayesian optimization",
  "tpe",
  "simulated annealing",
  "ant colony optimization",
  "grey wolf optimization"
]


[project.urls]
Homepage = "https://github.com/Faycal214/optiflowx"
Repository = "https://github.com/Faycal214/optiflowx"
Issues = "https://github.com/Faycal214/optiflowx/issues"
