"""Public API for discrete-time filtrations from MSPRO Chapter 5."""

from __future__ import annotations

from collections.abc import Sequence

from .martingale import Filtration as _Filtration


class Filtration(_Filtration):
    """Increasing sequence of finite sigma-fields represented by partitions."""

    @property
    def n_steps(self) -> int:
        """Return the number of filtration levels represented."""
        return len(self)

    def at(self, n: int):
        """Return ``F_n``."""
        return self[n]

    @classmethod
    def natural(cls, process: Sequence):
        """Construct the natural filtration generated by a finite process."""
        if not process:
            raise ValueError("process must not be empty")
        space = process[0].space
        if any(rv.space is not space for rv in process):
            raise ValueError("all variables must belong to the same space")
        from .partition import Partition

        partitions = []
        for n in range(len(process)):
            groups = {}
            for outcome in space.outcomes:
                key = tuple(process[k].values[outcome] for k in range(n + 1))
                groups.setdefault(key, set()).add(outcome)
            partitions.append(Partition.from_blocks(groups.values(), space))
        return cls(partitions)


__all__ = ["Filtration"]
