"""Discrete-time filtrations from MSPRO Chapter 5."""

from __future__ import annotations

from collections.abc import Sequence

from .partition import Partition
from .random_variable import RandomVariable


class Filtration:
    """Increasing sequence of finite sigma-fields represented by partitions."""

    def __init__(self, partitions: Sequence[Partition]) -> None:
        if not partitions:
            raise ValueError("a filtration must contain at least one partition")
        self.partitions = tuple(partitions)
        for previous, current in zip(self.partitions, self.partitions[1:]):
            if not current.refines(previous):
                raise ValueError("filtration partitions must be increasing")

    @property
    def n_steps(self) -> int:
        """Return the number of filtration levels."""
        return len(self.partitions)

    def __getitem__(self, n: int) -> Partition:
        return self.partitions[n]

    def __len__(self) -> int:
        return len(self.partitions)

    def at(self, n: int) -> Partition:
        """Return ``F_n``."""
        return self.partitions[n]

    @classmethod
    def natural(cls, process: Sequence[RandomVariable]) -> "Filtration":
        """Construct the natural filtration generated by a finite process."""
        if not process:
            raise ValueError("process must not be empty")
        space = process[0].space
        if any(rv.space is not space for rv in process):
            raise ValueError("all variables must belong to the same space")
        partitions = []
        for n in range(len(process)):
            groups = {}
            for outcome in space.outcomes:
                key = tuple(process[k].values[outcome] for k in range(n + 1))
                groups.setdefault(key, set()).add(outcome)
            partitions.append(Partition.from_blocks(groups.values(), space))
        return cls(partitions)

    def is_adapted(self, process: Sequence[RandomVariable]) -> bool:
        """Return whether the process is adapted to this filtration."""
        if len(process) > len(self):
            return False
        return all(process[n].space.check_measurable(process[n], self[n]) for n in range(len(process)))


__all__ = ["Filtration"]
