"""Public API for finite partitions used as sigma-fields in Chapter 4."""

from __future__ import annotations

from collections.abc import Iterable

from .conditional import Partition as _Partition


class Partition(_Partition):
    """Finite partition representing the information carried by a sigma-field.

    Blocks are pairwise disjoint non-empty subsets whose union is the finite
    sample space. The partition represents the finite information structure
    used for conditional expectation in the course.
    """

    @property
    def n_blocks(self) -> int:
        """Return the number of blocks in the partition."""
        return len(self.blocks)

    def contains(self, outcome) -> int:
        """Return the index of the block containing ``outcome``."""
        for index, block in enumerate(self.blocks):
            if outcome in block:
                return index
        raise ValueError(f"unknown outcome: {outcome!r}")

    @classmethod
    def from_blocks(cls, blocks: Iterable[Iterable], space):
        """Create a canonical partition after validating coverage and disjointness."""
        normalized = tuple(frozenset(block) for block in blocks)
        if not normalized or any(not block for block in normalized):
            raise ValueError("partition blocks must be non-empty")
        if set().union(*normalized) != set(space.outcomes):
            raise ValueError("partition must cover the probability space")
        if sum(map(len, normalized)) != len(space.outcomes):
            raise ValueError("partition blocks must be disjoint")
        return cls(normalized)

    @classmethod
    def generated_by(cls, rv):
        """Create the partition generated by the level sets of ``rv``."""
        groups = {}
        for outcome, value in rv.values.items():
            groups.setdefault(float(value), set()).add(outcome)
        return cls.from_blocks(groups.values(), rv.space)


__all__ = ["Partition"]
